spring:
  application:
    name: RealtimeAuctionSystem
  datasource:
    url: ${DB_URL}?rewriteBatchedStatements=true&cachePrepStmts=true&useServerPrepStmts=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 100
      minimum-idle: 20
      connection-timeout: 10000
      idle-timeout: 300000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 3000
      lettuce:
        pool:
          max-active: 50
          max-idle: 20
          min-idle: 10
          max-wait: 10000
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      acks: 1
      retries: 1
      batch-size: 16384
      compression-type: snappy
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        request.timeout.ms: 1000
        delivery.timeout.ms: 2500
        retry.backoff.ms: 200
        linger.ms: 10
    consumer:
      group-id: auction-db-sync-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        max.poll.interval.ms: 300000
        session.timeout.ms: 30000
        spring.json.trusted.packages: "*"

server:
  port: 8080
  servlet:
    context-path: /api
  tomcat:
    threads:
      max: 500
      min-spare: 100
    accept-count: 500
    connection-timeout: 20000

outbound:
  redirect-uri: http://localhost:5173/auth/callback
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}

jwt:
  access-key: ${JWT_ACCESS_KEY}
  refresh-key: ${JWT_REFRESH_KEY}
  valid-duration: 2 # in hours
  refreshable-duration: 48 # in hours

app:
  file:
    upload-dir: F:/bidding-platform/upload
    max-size: 5242880 # 5MB
    allowed-types: image/jpeg,image/png,image/webp,image/gif