---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ADMIN.
--- DateTime: 2/3/2026 8:49 AM
---

-- place_bid.lua
-- Xử lý toàn bộ bid logic: validate → anti-snipe → update
--
-- KEYS[1] = auction:{auctionId} (hash)
--
-- ARGV[1] = newPrice
-- ARGV[2] = bidderId
-- ARGV[3] = now (epoch seconds)
-- ARGV[4]  = maxExtension
--
-- Returns:
--   { 0, errorMessage }                          → Bid rejected
--   { 1, 'Success', 'normal', endTime }          → Bid success, no extension
--   { 1, 'Success', 'extended', newEndTime }     → Bid success, extended

local key = KEYS[1]
local newPrice = tonumber(ARGV[1])
local bidderId = ARGV[2]
local now = tonumber(ARGV[3])
local maxExtension = tonumber(ARGV[4])

-- 1. Check auction exists + status
local status = redis.call('HGET', key, 'status')
if status == false then
    return { 0, 'Auction not found' }
end
if status ~= 'LIVE' then
    return { 0, 'Auction is not live' }
end

-- 2. Anti-fraud: seller cannot bid own auction
local sellerId = redis.call('HGET', key, 'sellerId')
if sellerId == bidderId then
    return { 0, 'Cannot bid on your own auction' }
end

-- 3. Validate price
local currentPrice = tonumber(redis.call('HGET', key, 'currentPrice'))
local minStep = tonumber(redis.call('HGET', key, 'minStep'))
local minValidPrice = currentPrice + minStep

if newPrice < minValidPrice then
    return { 0, string.format('Bid must be at least %.2f', minValidPrice) }
end

-- 4. Anti-snipe check
local endTime = tonumber(redis.call('HGET', key, 'endTime'))
local antiSnipeSeconds = tonumber(redis.call('HGET', key, 'antiSnipeSeconds'))
local extensionSeconds = tonumber(redis.call('HGET', key, 'extensionSeconds'))
local extensionCount = tonumber(redis.call('HGET', key, 'extensionCount') or '0')

local extended = false
local finalEndTime = endTime
local secondsLeft = endTime - now

if secondsLeft <= antiSnipeSeconds then
    if extensionCount < maxExtension then
        -- Gia hạn
        finalEndTime = endTime + extensionSeconds
        redis.call('HSET', key, 'endTime', tostring(finalEndTime))
        redis.call('HSET', key, 'extensionCount', tostring(extensionCount + 1))
        extended = true
    end
    -- Nếu đã max extension → vẫn cho bid, chỉ không extend
end

-- 5. Update bid (ATOMIC)
redis.call('HSET', key, 'currentPrice', tostring(newPrice))
redis.call('HSET', key, 'highestBidderId', bidderId)
redis.call('HSET', key, 'lastBidTime', tostring(now))
redis.call('HINCRBY', key, 'bidCount', 1)
redis.call('HINCRBY', key, 'version', 1)

-- 6. Return result
if extended then
    return { 1, 'Success', 'extended', tostring(finalEndTime) }
end
return { 1, 'Success', 'normal', tostring(finalEndTime) }