---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ADMIN.
--- DateTime: 2/3/2026 8:49 AM
---

-- place_bid.lua
-- Xử lý toàn bộ bid logic: validate → anti-snipe → update
--
-- KEYS[1] = auction:{auctionId} (hash)
--
-- ARGV[1] = newPrice
-- ARGV[2] = bidderId
-- ARGV[3] = now (epoch seconds)
-- ARGV[4]  = maxExtension
--
-- Returns:
--   { 0, errorMessage }                          → Bid rejected
--   { 1, 'Success', 'normal', endTime }          → Bid success, no extension
--   { 1, 'Success', 'extended', newEndTime }     → Bid success, extended

local key = KEYS[1]
local newPrice = tonumber(ARGV[1])
local bidderId = ARGV[2]
local now = tonumber(ARGV[3])
local maxExtension = tonumber(ARGV[4])

-- 1. Dùng HMGET lấy 1 lượt toàn bộ field cần thiết
local data = redis.call('HMGET', key, 'status', 'sellerId', 'currentPrice', 'minStep', 'endTime', 'antiSnipeSeconds', 'extensionSeconds', 'extensionCount')

local status = data[1]
if not status then return { 0, 'Auction not found' } end
if status ~= 'LIVE' then return { 0, 'Auction is not live' } end

local sellerId = data[2]
if sellerId == bidderId then return { 0, 'Cannot bid on your own auction' } end

local currentPrice = tonumber(data[3] or '0')
local minStep = tonumber(data[4] or '0')
if newPrice < (currentPrice + minStep) then
    return { 0, string.format('Bid must be at least %.2f', currentPrice + minStep) }
end

-- 2. Logic Anti-snipe
local endTime = tonumber(data[5] or '0')
local antiSnipeSeconds = tonumber(data[6] or '0')
local extensionSeconds = tonumber(data[7] or '0')
local extensionCount = tonumber(data[8] or '0')

local extended = false
local finalEndTime = endTime
local secondsLeft = endTime - now

if secondsLeft <= antiSnipeSeconds and extensionCount < maxExtension then
    finalEndTime = endTime + extensionSeconds
    extended = true
end

-- 3. Ghi dữ liệu (Dùng HMSET để gom các lệnh SET)
local updates = {
    'currentPrice', tostring(newPrice),
    'highestBidderId', bidderId,
    'lastBidTime', tostring(now),
    'endTime', tostring(finalEndTime)
}

local nextExtensionCount = extensionCount
if extended then
    nextExtensionCount = extensionCount + 1
    table.insert(updates, 'extensionCount')
    table.insert(updates, tostring(nextExtensionCount))
end

redis.call('HMSET', key, unpack(updates))
redis.call('HINCRBY', key, 'bidCount', 1)
redis.call('HINCRBY', key, 'version', 1)

return { 1, 'Success', extended and 'extended' or 'normal', tostring(finalEndTime), nextExtensionCount }